CREATE USER api_user
WITH
    PASSWORD 'api_pass';

GRANT CONNECT ON DATABASE surveydb TO api_user;

GRANT USAGE ON SCHEMA public TO api_user;

GRANT
SELECT
,
    INSERT,
UPDATE,
DELETE ON ALL TABLES IN SCHEMA public TO api_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT
SELECT
,
    INSERT,
UPDATE,
DELETE ON TABLES TO api_user;

GRANT USAGE,
SELECT
    ON ALL SEQUENCES IN SCHEMA public TO api_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE,
SELECT
    ON SEQUENCES TO api_user;